import { Data, IProductInput, IUserInput } from "@/types"
import { toSlug } from "./utils"
import bcrypt from "bcryptjs"

const products: IProductInput[] = [
    // Casuals
    {
      name: 'Women’s Casual Chic Sleeveless Tank Top Set',
      slug: toSlug('Women’s Casual Chic Sleeveless Tank Top Set'),
      category: 'Casuals',
      images: ['/images/p1-1.jpg', '/images/p1-2.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 29.99,
      listPrice: 39.99,
      brand: 'Zara',
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      numSales: 9,
      countInStock: 11,
      description:
      'Stay effortlessly stylish with this sleeveless ribbed tank top and belted high-waist pants combo. Perfect for sunny days and casual outings.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Mint Green', 'Beige', 'Black'],
  
      reviews: [],
    },
    {
      name: 'Women’s Chunky Knit Cardigan with White Inner Top',
      slug: toSlug('Women’s Chunky Knit Cardigan with White Inner Top'),
      category: 'Casuals',
      images: [
        '/images/p2-1.jpg',
        '/images/p2-2.jpg',
        '/images/p2-3.jpg', 
      ],
      tags: ['featured'],
      isPublished: true,
      price: 34.99,
      listPrice: 49.99,
      brand: 'H&M',
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 29,
      countInStock: 12,
      description:
      'This cozy chunky knit cardigan is perfect for layering in cooler seasons. Styled with a classic white knit top for a comfy and stylish everyday look.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy Blue', 'White', 'Heather Grey'],
  
      reviews: [],
    },
    {
      name: 'Women’s Wool Overcoat with Wide-Brim Hat',
      slug: toSlug('Women’s Wool Overcoat with Wide-Brim Hat'),
      category: 'Formals',
      images: ['/images/p3-1.jpg', '/images/p3-2.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 59.99,
      listPrice: 79.99,
      brand: 'Mango',
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 55,
      countInStock: 13,
      description:
      'Elegant and bold, this wool-blend overcoat in vibrant pink pairs beautifully with a classic wide-brim hat. Ideal for stylish winter outings or formal occasions.',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Pink', 'Black', 'Camel'],
  
      reviews: [],
    },
    {
      name: "Women's Polka Dot Chiffon Blouse",
      slug: toSlug("Women's Polka Dot Chiffon Blouse"),
      category: "Casuals",
      images: [
        '/images/p4-1.jpg', 
        '/images/p4-2.jpg',
        '/images/p4-3.jpg',
      ],
      tags: ['todays-deal'],
      isPublished: true,
      price: 39.99,
      listPrice: 49.99,
      brand: "ChicStyle",
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 54,
      countInStock: 14,
      description: "Lightweight and stylish chiffon blouse featuring a classic polka dot pattern. Perfect for everyday wear or dressing up for a casual event. Features long, slightly puffed sleeves and a button-up front.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black", "White", "Blue"],
  
      reviews: [],
    },
    {
      name: "Women's Denim Jacket with Black Hat",
      slug: toSlug("Women's Denim Jacket with Black Hat"),
      category: "Casuals",
      images: ['/images/p5-1.jpg', '/images/p5-2.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 45.99,
      listPrice: 59.99,
      brand: "UrbanStyle",
      avgRating: 3.66,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      numSales: 54,
      countInStock: 15,
      description: "Stylish denim jacket paired with a chic black hat.  Perfect for a trendy, casual look. The jacket features a classic design with button closure and a comfortable fit.",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Light Blue", "Black", "White"],
  
      reviews: [],
    },
    {
      name: "Women's Pink Blazer with Jeans",
      slug: toSlug("Women's Pink Blazer with Jeans"),
      category: "Casuals",
      images: [
        '/images/p6-1.jpg', 
        '/images/p6-2.jpg',
        '/images/p6-3.jpg',],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 69.99,
      listPrice: 89.99,
      brand: "ChicStyle",
      avgRating: 3.46,
      numReviews: 13,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 16,
      numSales: 56,
      description: "Stylish pink blazer paired with classic blue jeans. This outfit is perfect for a trendy, casual look. The blazer features a relaxed fit and can be dressed up or down.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Pink", "Blue", "White"],
  
      reviews: [],
    },
    {
      name: "Women's Pink Faux",
      slug: toSlug("Women's Pink Faux Fur Coat"),
      category: "Outerwear",
      images: ['/images/p7-1.jpg', '/images/p7-2.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 129.99,
      listPrice: 159.99,
      brand: "GlamourStyle",
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      countInStock: 54,
      numSales: 21,
      description: "Luxurious pink faux fur coat, perfect for making a bold fashion statement. This eye-catching coat is both stylish and comfortable, ideal for evening events or adding flair to your winter wardrobe.",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Pink", "White", "Lavender"],
  
      reviews: [],
    },
    {
      name: "Women's Pink Faux Fur Coat",
      slug: toSlug("Women's Pink Faux"),
      category: "Outerwear",
      images: ['/images/p8-1.jpg'],
      tags: ['featured'],
      isPublished: true,
      price: 129.99,
      listPrice: 159.99,
      brand: "GlamourStyle",
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 22,
      numSales: 54,
      description: "Luxurious pink faux fur coat, perfect for making a bold fashion statement. This eye-catching coat is both stylish and comfortable, ideal for evening events or adding flair to your winter wardrobe.",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Pink", "Black", "Red"],
  
      reviews: [],
    },
    {
      name: "Women's Printed Dress with White Coat and Hat",
      slug: toSlug("Women's Printed Dress with White Coat and Hat"),
      category: "Dresses",
      images: ['/images/p9-1.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 79.99,
      listPrice: 99.99,
      brand: "ElegantStyle",
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 23,
      numSales: 54,
      description: "Elegant printed dress paired with a stylish white coat and hat. This sophisticated ensemble is perfect for special occasions or a chic daytime look.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black", "White", "Beige"],
  
      reviews: [],
    },
    {
      name: "Women's Blue Power Suit",
      slug: toSlug("Women's Blue Power Suit"),
      category: "Formals",
      images: ['/images/p10-1.jpg', '/images/p10-2.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 179.99,
      listPrice: 229.99,
      brand: "ExecutiveStyle",
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 24,
      numSales: 53,
      description: "Elegant blue power suit for women. This sophisticated ensemble is perfect for professional settings and formal occasions. The suit features a tailored fit and can be accessorized with a variety of blouses and accessories.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Blue", "Black", "Gray"],
  
      reviews: [],
    },
    {
      name: "Women's Yellow Blazer with Straw Hat",
      slug: toSlug("Women's Yellow Blazer with Straw Hat"),
      category: "Casuals",
      images: ['/images/p11-1.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 89.99,
      listPrice: 110.00,
      brand: "BohoChic",
      avgRating: 3.66,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 25,
      numSales: 48,
      description: "Stylish yellow blazer paired with a trendy straw hat.  This vibrant and chic ensemble is perfect for a sunny day out or a casual gathering.  The blazer features a relaxed fit and can be easily dressed up or down.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Yellow", "Beige", "White"],
  
      reviews: [],
    },
    {
      name: "Women's Orange Dress with Straw Hat and Bag",
      slug: toSlug("Women's Orange Dress with Straw Hat and Bag"),
      category: "Dresses",
      images: ['/images/p12-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 74.99,
      listPrice: 94.99,
      brand: "BohoChic",
      avgRating: 3.46,
      numReviews: 13,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 26,
      numSales: 48,
      description: "Flowy orange dress paired with a stylish straw hat and woven bag.  This bohemian-inspired outfit is perfect for a relaxed, sunny day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Orange", "Beige", "Brown"],
  
      reviews: [],
    },
  
    {
      name: "Women's Printed Crop Top and Denim Shorts",
      slug: toSlug("Women's Printed Crop Top and Denim Shorts"),
      category: "Casuals",
      images: ['/images/p13-1.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 49.99,
      listPrice: 69.99,
      brand: "SummerVibes",
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      countInStock: 31,
      numSales: 48,
      description: "Chic printed crop top paired with denim shorts. This stylish and comfortable outfit is perfect for a sunny day out or a casual gathering.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black", "Blue", "Brown"],
  
      reviews: [],
    },
    {
      name: "Women's Wool Coats with Hats",
      slug: toSlug("Women's Wool Coats with Hats"),
      category: "Outerwear",
      images: ['/images/p14-1.jpg'],
      tags: ['featured'],
      isPublished: true,
      price: 249.99,
      listPrice: 300.00,
      brand: "ChicStyle",
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 32,
      numSales: 48,
      description: "Elegant wool coats paired with stylish hats. This sophisticated look is perfect for cooler weather, offering both warmth and high-fashion appeal.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Pink", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Purple Top with Jeans and Hat",
      slug: toSlug("Women's Purple Top with Jeans and Hat"),
      category: "Casuals",
      images: ['/images/p15-1.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 64.99,
      listPrice: 79.99,
      brand: "StreetStyle",
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 33,
      numSales: 48,
      description: "Chic purple top paired with jeans and a stylish hat. This trendy outfit is perfect for a casual day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Purple", "Blue", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Black Leather Jacket",
      slug: toSlug("Women's Black Leather Jacket"),
      category: "Outerwear",
      images: ['/images/p16-1.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 199.99,
      listPrice: 249.99,
      brand: "UrbanEdge",
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 34,
      numSales: 48,
      description: "Classic black leather jacket for women. This timeless piece is perfect for adding an edgy touch to any outfit.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black"],
  
      reviews: [],
    },
    {
      name: "Women's Pink Coat with Black Hat and Bag",
      slug: toSlug("Women's Pink Coat with Black Hat and Bag"),
      category: "Outerwear",
      images: ['/images/p17-1.jpg', '/images/p17-2.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 219.99,
      listPrice: 279.99,
      brand: "CityStyle",
      avgRating: 3.66,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 35,
      numSales: 48,
      description: "Elegant pink coat paired with a black hat and a stylish black bag. This sophisticated outfit is perfect for a fashionable day out in the city.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Pink", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Beige Trench Coat with Black Hat",
      slug: toSlug("Women's Beige Trench Coat with Black Hat"),
      category: "Outerwear",
      images: ['/images/p18-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 189.99,
      listPrice: 239.99,
      brand: "ClassicStyle",
      avgRating: 3.46,
      numReviews: 13,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 36,
      numSales: 49,
      description: "Elegant beige trench coat paired with a stylish black hat. This timeless combination is perfect for a sophisticated and polished look.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Beige", "Black", "White"],
  
      reviews: [],
    },
  
    {
      name: "Women's Striped Dress with Hat and Shopping Bag",
      slug: toSlug("Women's Striped Dress with Hat and Shopping Bag"),
      category: "Dresses",
      images: ['/images/p19-1.jpg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 69.99,
      listPrice: 89.99,
      brand: "SummerStyle",
      avgRating: 4.71,
      numReviews: 7,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 2 },
        { rating: 5, count: 5 },
      ],
      countInStock: 41,
      numSales: 48,
      description: "Casual striped dress paired with a stylish hat and a shopping bag. This comfortable and chic outfit is perfect for a day out shopping or a casual outing.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["light blue", "Beige", "Pink"],
  
      reviews: [],
    },
    {
      name: "Women's Red Sweater with Glasses and Hat",
      slug: toSlug("Women's Red Sweater with Glasses and Hat"),
      category: "Casuals",
      images: ['/images/p20-1.jpg'],
      tags: ['featured'],
      isPublished: true,
      price: 79.99,
      listPrice: 99.99,
      brand: "StreetStyle",
      avgRating: 4.2,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 0 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 42,
      numSales: 50,
      description: "Stylish red sweater paired with glasses and a hat. This trendy and cozy outfit is perfect for a casual day out in the city.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Red", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Beige Trench Coat ",
      slug: toSlug("Women's Beige Trench Coat"),
      category: "Outerwear",
      images: ['/images/p21-1.jpg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 189.99,
      listPrice: 239.99,
      brand: "ClassicStyle",
      avgRating: 4,
      numReviews: 12,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 0 },
        { rating: 3, count: 2 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 43,
      numSales: 72,
      description: "Elegant beige trench coat paired with a stylish black hat. This timeless combination is perfect for a sophisticated and polished look.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Beige", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Yellow Sweater with Shopping Bags",
      slug: toSlug("Women's Yellow Sweater with Shopping Bags"),
      category: "Casuals",
      images: ['/images/p22-1.jpg'],
      tags: ['todays-deal'],
      isPublished: true,
      price: 69.99,
      listPrice: 89.99,
      brand: "UrbanStyle",
      avgRating: 3.85,
      numReviews: 14,
      ratingDistribution: [
        { rating: 1, count: 0 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 44,
      numSales: 72,
      description: "Stylish yellow sweater paired with shopping bags. This casual and trendy outfit is perfect for a day out shopping.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Yellow", "Blue"],
  
      reviews: [],
    },
    {
      name: "Women's Black Leather Jacket with Scarf",
      slug: toSlug("Women's Black Leather Jacket with Scarf"),
      category: "Outerwear",
      images: ['/images/p23-1.jpg'],
      tags: ['new-arrival', 'featured'],
      isPublished: true,
      price: 219.99,
      listPrice: 279.99,
      brand: "UrbanEdge",
      avgRating: 3.66,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 5 },
      ],
      countInStock: 45,
      numSales: 64,
      description: "Edgy black leather jacket paired with a cozy scarf. This stylish combination is perfect for a cool day out in the city.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black", "Gray"],
  
      reviews: [],
    },
    {
      name: "Women's Black Blazer with White Sunglasses",
      slug: toSlug("Women's Black Blazer with White Sunglasses"),
      category: "Formals",
      images: ['/images/p24-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 129.99,
      listPrice: 159.99,
      brand: "ChicStyle",
      avgRating: 3.46,
      numReviews: 13,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Elegant black blazer paired with stylish white sunglasses. This sophisticated look is perfect for a professional setting or a chic day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Black", "White"],
  
      reviews: [],
    },
    {
      name: "Women's Casual Top with Shopping Bags",
      slug: toSlug("Women's Casual Top with Shopping Bags"),
      category: "Casuals",
      images: ['/images/p25-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 59.99,
      listPrice: 79.99,
      brand: "UrbanStyle",
      avgRating: 4.33,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Casual top paired with shopping bags. This vibrant and fun outfit is perfect for a day out shopping.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Brown", "Blue"],
  
      reviews: [],
    },
    {
      name: "Women's Tweed Blazer with Hat",
      slug: toSlug("Women's Tweed Blazer with Hat"),
      category: "Outerwear",
      images: ['/images/p26-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 149.99,
      listPrice: 189.99,
      brand: "ClassicStyle",
      avgRating: 4.50,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Elegant tweed blazer paired with a stylish hat. This sophisticated and timeless look is perfect for a refined and polished appearance.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Brown", "Beige"],
  
      reviews: [],
    },
    {
      name: "Women's Yellow Blazer with Striped Pants",
      slug: toSlug("Women's Yellow Blazer with Striped Pants"),
      category: "Casuals",
      images: ['/images/p27-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 99.99,
      listPrice: 129.99,
      brand: "ChicStyle",
      avgRating: 4.80,
      numReviews: 8,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Stylish yellow blazer paired with striped pants. This vibrant and trendy outfit is perfect for a fashionable day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Yellow", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's Gray Poncho with Black Hat",
      slug: toSlug("Women's Gray Poncho with Black Hat"),
      category: "Outerwear",
      images: ['/images/p28-1.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 119.99,
      listPrice: 149.99,
      brand: "BohoStyle",
      avgRating: 4.06,
      numReviews: 10,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Cozy gray poncho paired with a stylish black hat. This comfortable and chic outfit is perfect for a relaxed day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Gray", "Black"],
  
      reviews: [],
    },
    {
      name: "Women's White Sweater with Hat",
      slug: toSlug("Women's White Sweater with Hat"),
      category: "Casuals",
      images: ['/images/p29-1.jpg', '/images/p29-2.jpg',  '/images/p29-3.jpg'],
      tags: ['best-seller', 'todays-deal'],
      isPublished: true,
      price: 69.99,
      listPrice: 89.99,
      brand: "StreetStyle",
      avgRating: 4.46,
      numReviews: 15,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 4 },
        { rating: 5, count: 3 },
      ],
      countInStock: 46,
      numSales: 48,
      description: "Cozy white sweater paired with a stylish hat. This comfortable and chic outfit is perfect for a casual day out.",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["White", "Black"],
  
      reviews: [],
    },
  ]

//Users
  const users: IUserInput[] = [
    {
      name: 'Mahedy',
      email: 'mahedyhasan873@gmail.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'Admin',
      address: {
        fullName: 'Mahedy Hasan',
        street: 'XYZ',
        city: 'Chattogram',
        province: 'CTG',
        postalCode: '12345',
        country: 'Bangladesh',
        phone: '123-456-7890',
      },
      paymentMethod: 'Stripe',
      emailVerified: false,
    },
    {
      name: 'Jane',
      email: 'jane@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Jane Harris',
        street: '222 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '1002',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Cash On Delivery',
      emailVerified: false,
    },
    {
      name: 'Jack',
      email: 'jack@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Jack Ryan',
        street: '333 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '1003',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'PayPal',
      emailVerified: false,
    },
    {
      name: 'Sarah',
      email: 'sarah@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Sarah Smith',
        street: '444 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '1005',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Cash On Delivery',
      emailVerified: false,
    },
    {
      name: 'Michael',
      email: 'michael@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'John Alexander',
        street: '555 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '1006',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'PayPal',
      emailVerified: false,
    },
    {
      name: 'Emily',
      email: 'emily@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Emily Johnson',
        street: '666 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '10001',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Stripe',
      emailVerified: false,
    },
    {
      name: 'Alice',
      email: 'alice@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Alice Cooper',
        street: '777 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '10007',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Cash On Delivery',
      emailVerified: false,
    },
    {
      name: 'Tom',
      email: 'tom@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Tom Hanks',
        street: '888 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '10008',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Stripe',
      emailVerified: false,
    },
    {
      name: 'Linda',
      email: 'linda@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Linda Holmes',
        street: '999 Main St',
        city: 'New York',
        province: 'NY',
        postalCode: '10009',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'PayPal',
      emailVerified: false,
    },
    {
      name: 'George',
      email: 'george@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'George Smith',
        street: '101 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10010',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Stripe',
      emailVerified: false,
    },
    {
      name: 'Jessica',
      email: 'jessica@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Jessica Brown',
        street: '102 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10011',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Cash On Delivery',
      emailVerified: false,
    },
    {
      name: 'Chris',
      email: 'chris@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Chris Evans',
        street: '103 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10012',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'PayPal',
      emailVerified: false,
    },
    {
      name: 'Samantha',
      email: 'samantha@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Samantha Wilson',
        street: '104 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10013',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Stripe',
      emailVerified: false,
    },
    {
      name: 'David',
      email: 'david@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'David Lee',
        street: '105 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10014',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'Cash On Delivery',
      emailVerified: false,
    },
    {
      name: 'Anna',
      email: 'anna@example.com',
      password: bcrypt.hashSync('123456', 5),
      role: 'User',
      address: {
        fullName: 'Anna Smith',
        street: '106 First Ave',
        city: 'New York',
        province: 'NY',
        postalCode: '10015',
        country: 'USA',
        phone: '123-456-7890',
      },
      paymentMethod: 'PayPal',
      emailVerified: false,
    },
  ]

  //review
  const reviews = [
    {
      rating: 1,
      title: 'Poor quality',
      comment:
        'Very disappointed. The item broke after just a few uses. Not worth the money.',
    },
    {
      rating: 2,
      title: 'Disappointed',
      comment:
        "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
    },
    {
      rating: 2,
      title: 'Needs improvement',
      comment:
        "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
    },
    {
      rating: 3,
      title: 'not bad',
      comment:
        'This product is decent, the quality is good but it could use some improvements in the details.',
    },
    {
      rating: 3,
      title: 'Okay, not great',
      comment:
        'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
    },
    {
      rating: 3,
      title: 'Good product',
      comment:
        'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
    },
    {
      rating: 4,
      title: 'Pretty good',
      comment:
        "Solid product! Great value for the price, but there's room for minor improvements.",
    },
    {
      rating: 4,
      title: 'Very satisfied',
      comment:
        'Good product! High quality and worth the price. Would consider buying again.',
    },
    {
      rating: 4,
      title: 'Absolutely love it!',
      comment:
        'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
    },
    {
      rating: 4,
      title: 'Exceeded expectations!',
      comment:
        'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
    },
    {
      rating: 5,
      title: 'Perfect purchase!',
      comment:
        "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
    },
    {
      rating: 5,
      title: 'Highly recommend',
      comment:
        "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
    },
    {
      rating: 5,
      title: 'Just what I needed',
      comment:
        'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
    },
    {
      rating: 5,
      title: 'Excellent choice!',
      comment:
        'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
    },
    {
      rating: 5,
      title: "Couldn't ask for more!",
      comment:
        "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
    },
  ]



const data: Data = {
     
    headerMenus: [
      {
        name: "Today's Deal",
        href: '/search?tag=todays-deal',
      },
      {
        name: 'New Arrivals',
        href: '/search?tag=new-arrival',
      },
      {
        name: 'Featured Products',
        href: '/search?tag=featured',
      },
      {
        name: 'Best Sellers',
        href: '/search?tag=best-seller',
      },
      {
        name: 'Browsing History',
        href: '/#browsing-history',
      },
      {
        name: 'Customer Service',
        href: '/page/customer-service',
      },
      {
        name: 'About Us',
        href: '/page/about-us',
      },
      {
        name: 'Help',
        href: '/page/help',
      },
    ],
    //Carousels
    carousels: [
        {
          title: 'From Streetwear to Statement — We’ve Got Your Look',
          buttonCaption: 'Shop Now',
          image: '/images/banner3.png',
          url: '/search?category=Casuals',
          isPublished: true,
        },
        {
          title: 'Step Into Fashion. Step Into Confidence.',
          buttonCaption: 'Shop Now',
          image: '/images/banner1.png',
          url: '/search?category=Bold',
          isPublished: true,
        },
        {
          title: 'Unleash Your Style — Wear the Trend, Be the Trend',
          buttonCaption: 'See More',
          image: '/images/banner2.png',
          url: '/search?category=Trendy',
          isPublished: true,
        },
      ],
      //webPages

      webPages: [
        {
          title: 'About Us',
          slug: 'about-us',
          content: `Welcome to [Your Store Name], your trusted destination for quality products and exceptional service. Our journey began with a mission to bring you the best shopping experience by offering a wide range of products at competitive prices, all in one convenient platform.
    
    At [Your Store Name], we prioritize customer satisfaction and innovation. Our team works tirelessly to curate a diverse selection of items, from everyday essentials to exclusive deals, ensuring there's something for everyone. We also strive to make your shopping experience seamless with fast shipping, secure payments, and excellent customer support.
    
    As we continue to grow, our commitment to quality and service remains unwavering. Thank you for choosing [Your Store Name]—we look forward to being a part of your journey and delivering value every step of the way.`,
          isPublished: true,
        },
        {
          title: 'Contact Us',
          slug: 'contact-us',
          content: `We’re here to help! If you have any questions, concerns, or feedback, please don’t hesitate to reach out to us. Our team is ready to assist you and ensure you have the best shopping experience.
    
    **Customer Support**
    For inquiries about orders, products, or account-related issues, contact our customer support team:
    - **Email:** support@example.com
    - **Phone:** +1 (123) 456-7890
    - **Live Chat:** Available on our website from 9 AM to 6 PM (Monday to Friday).
    
    **Head Office**
    For corporate or business-related inquiries, reach out to our headquarters:
    - **Address:** 1234 E-Commerce St, Suite 567, Business City, BC 12345
    - **Phone:** +1 (987) 654-3210
    
    We look forward to assisting you! Your satisfaction is our priority.
    `,
          isPublished: true,
        },
        {
          title: 'Help',
          slug: 'help',
          content: `Welcome to our Help Center! We're here to assist you with any questions or concerns you may have while shopping with us. Whether you need help with orders, account management, or product inquiries, this page provides all the information you need to navigate our platform with ease.
    
    **Placing and Managing Orders**
    Placing an order is simple and secure. Browse our product categories, add items to your cart, and proceed to checkout. Once your order is placed, you can track its status through your account under the "My Orders" section. If you need to modify or cancel your order, please contact us as soon as possible for assistance.
    
    **Shipping and Returns**
    We offer a variety of shipping options to suit your needs, including standard and express delivery. For detailed shipping costs and delivery timelines, visit our Shipping Policy page. If you're not satisfied with your purchase, our hassle-free return process allows you to initiate a return within the specified timeframe. Check our Returns Policy for more details.
    
    **Account and Support**
    Managing your account is easy. Log in to update your personal information, payment methods, and saved addresses. If you encounter any issues or need further assistance, our customer support team is available via email, live chat, or phone. Visit our Contact Us page for support hours and contact details.`,
          isPublished: true,
        },
        {
          title: 'Privacy Policy',
          slug: 'privacy-policy',
          content: `We value your privacy and are committed to protecting your personal information. This Privacy Notice explains how we collect, use, and share your data when you interact with our services. By using our platform, you consent to the practices described herein.
    
    We collect data such as your name, email address, and payment details to provide you with tailored services and improve your experience. This information may also be used for marketing purposes, but only with your consent. Additionally, we may share your data with trusted third-party providers to facilitate transactions or deliver products.
    
    Your data is safeguarded through robust security measures to prevent unauthorized access. However, you have the right to access, correct, or delete your personal information at any time. For inquiries or concerns regarding your privacy, please contact our support team.`,
          isPublished: true,
        },
        {
          title: 'Conditions of Use',
          slug: 'conditions-of-use',
          content: `Welcome to [Ecommerce Website Name]. By accessing or using our website, you agree to comply with and be bound by the following terms and conditions. These terms govern your use of our platform, including browsing, purchasing products, and interacting with any content or services provided. You must be at least 18 years old or have the consent of a parent or guardian to use this website. Any breach of these terms may result in the termination of your access to our platform.
    
    We strive to ensure all product descriptions, pricing, and availability information on our website are accurate. However, errors may occur, and we reserve the right to correct them without prior notice. All purchases are subject to our return and refund policy. By using our site, you acknowledge that your personal information will be processed according to our privacy policy, ensuring your data is handled securely and responsibly. Please review these terms carefully before proceeding with any transactions.
    `,
          isPublished: true,
        },
        {
          title: 'Customer Service',
          slug: 'customer-service',
          content: `At [Your Store Name], our customer service team is here to ensure you have the best shopping experience. Whether you need assistance with orders, product details, or returns, we are committed to providing prompt and helpful support.
    
    If you have questions or concerns, please reach out to us through our multiple contact options:
    - **Email:** support@example.com
    - **Phone:** +1 (123) 456-7890
    - **Live Chat:** Available on our website for instant assistance
    
    We also provide helpful resources such as order tracking, product guides, and FAQs to assist you with common inquiries. Your satisfaction is our priority, and we’re here to resolve any issues quickly and efficiently. Thank you for choosing us!`,
          isPublished: true,
        },
        {
          title: 'Returns Policy',
          slug: 'returns-policy',
          content: 'Returns Policy Content',
          isPublished: true,
        },
        {
          title: 'Careers',
          slug: 'careers',
          content: 'careers Content',
          isPublished: true,
        },
        {
          title: 'Blog',
          slug: 'blog',
          content: 'Blog Content',
          isPublished: true,
        },
        {
          title: 'Sell Products',
          slug: 'sell',
          content: `Sell Products Content`,
          isPublished: true,
        },
        {
          title: 'Become Affiliate',
          slug: 'become-affiliate',
          content: 'Become Affiliate Content',
          isPublished: true,
        },
        {
          title: 'Advertise Your Products',
          slug: 'advertise',
          content: 'Advertise Your Products',
          isPublished: true,
        },
        {
          title: 'Shipping Rates & Policies',
          slug: 'shipping',
          content: 'Shipping Rates & Policies',
          isPublished: true,
        },
      ],

      products,
      users,
      reviews,
  }
  
  
  export default data